'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowDown, ArrowRight, Award, BadgeCheck, BookOpen, CalendarDays, Camera, Check, CheckCircle2, ChevronRight, Clock3, Flag, Footprints, HeartHandshake, History, Home, Layers3, LockKeyhole, MapPin, MessageCircle, Plus, Search, ShieldCheck, Sparkles, Sprout, Users, WandSparkles, X } from 'lucide-react'
import { ActivityEditor } from '../../components/Editors'
import type { Activity, TalentProfile } from '../talent/types'
import { SOURCE_LABELS } from '../talent/types'
import { SelfWorkspace } from '../talent/components/self-workspace'
import { ProfileDetail, QuickRecommendation, SupporterSearch, TeamBuilder } from '../talent/components/talent-app'
import { TalentAvatar, TalentModal, completeness } from '../talent/components/talent-ui'
import { boardApi } from './client'
import { TalentIllustration } from '../talent/components/talent-illustration'
import { SkillAgreementButton } from '../talent/components/skill-agreement-button'
import { BoardAccountSettings, BoardMyPage } from './account-pages'
import { AccountMenu } from './account-menu'
import type { BoardBootstrap, DemoMission } from './model'
import '../talent/talent.css'
import './board.css'

const VIEWS=['home','missions','history','account','settings','talent','profile','suggestions','interview','recommendations','supporters','team','activities','about'] as const
type View=typeof VIEWS[number]
const titles:Record<View,string>={home:'ホーム',missions:'ミッションを探す',history:'あなたの活動履歴',account:'マイページ',settings:'アカウント',talent:'マイタレント',profile:'プロフィールを編集',suggestions:'見つかったスキルを確認',interview:'AIと経験をふりかえる',recommendations:'仲間の強みを推薦',supporters:'活動に合う仲間を探す',team:'チームをつくる',activities:'活動を管理',about:'この統合デモについて'}
const icons={poster:Flag,camera:Camera,people:Users,sns:BookOpen}
const teamDefault='10月10日 横浜駅街宣 13〜17時。音響1名、撮影1名、ハガシ2名、ビラ配り4名、初参加者フォロー1名'
const date=(value:string)=>new Date(value).toLocaleDateString('ja-JP',{month:'long',day:'numeric'})

export default function ActionBoardDemo({initialView}:{initialView:string}) {
  const [view,setView]=useState<View>(VIEWS.includes(initialView as View)?initialView as View:'home')
  const [data,setData]=useState<BoardBootstrap|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState('')
  const [mission,setMission]=useState<DemoMission|null>(null),[person,setPerson]=useState<string|null>(null),[recommend,setRecommend]=useState<TalentProfile|null>(null)
  const [activity,setActivity]=useState<Activity|'new'|null>(null),[teamPrompt,setTeamPrompt]=useState(teamDefault)
  async function refresh(){setData(await boardApi.load())}
  useEffect(()=>{refresh().catch(cause=>setError(cause.message))},[])
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer)},[toast])
  useEffect(()=>{const back=()=>{const part=window.location.pathname.split('/').filter(Boolean)[1];setView(VIEWS.includes(part as View)?part as View:'home')};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[])
  function navigate(next:string){if(!VIEWS.includes(next as View))return;setView(next as View);setError('');window.history.pushState(null,'',`/action-board-demo${next==='home'?'':`/${next}`}`);window.scrollTo({top:0,behavior:'instant'})}
  async function action(payload:Record<string,unknown>){await boardApi.action(payload);await refresh();setToast(payload.action==='suggestion.review'?'確認結果を保存しました':'デモに保存しました')}
  async function switchAccount(id:string){setBusy(true);setError('');setMission(null);setPerson(null);setRecommend(null);setActivity(null);try{await boardApi.switchAccount(id);await refresh();navigate(id==='staff-demo'?'supporters':'home')}catch(cause){setError(cause instanceof Error?cause.message:'切り替えできませんでした')}finally{setBusy(false)}}
  if(!data)return <div className="talent-app ab-demo ab-loading"><Sprout size={36}/><h1>Action Board × Talent</h1><p>{error||'統合デモを準備しています…'}</p>{error&&<button className="ab-button primary" onClick={()=>switchAccount('s1')}>デモアカウントを選び直す</button>}</div>
  const staff=data.actor.role==='staff',self=data.profiles.find(profile=>profile.id===data.actor.id),pending=data.suggestions.filter(item=>item.status==='pending').length
  const selected=data.profiles.find(profile=>profile.id===person)
  const mine=['account','settings','talent','profile','suggestions','interview','recommendations','history'].includes(view)
  const talentView=['talent','profile','suggestions','interview','recommendations'].includes(view)
  const staffView=staff&&['supporters','team','activities'].includes(view)
  const forbidden=(staff&&mine)||(!staff&&['supporters','team','activities'].includes(view))
  return <div className={`talent-app ab-demo ${talentView?'ab-talent-surface':''} ${staffView?'ab-staff-surface':''}`}>
    <div className="ab-demo-bar"><span><ShieldCheck size={14}/>非公式・ローカル統合デモ <i/>すべて架空データ／公式環境に未接続</span><button onClick={()=>navigate('about')}>このデモについて <ChevronRight size={13}/></button></div>
    <header className="ab-header"><button className="ab-brand" onClick={()=>navigate('home')}><span className="ab-brand-symbol"><span>チーム<br/>みらい</span></span><span>アクションボード</span></button><nav aria-label="統合デモのメインメニュー"><button onClick={()=>navigate('home')} className={view==='home'?'active':''}><Home size={16}/>ホーム</button></nav><AccountMenu key={data.actor.id} name={data.actor.name} staff={staff} onNavigate={navigate}/></header>
    <div className="ab-role-strip"><span><span className="ab-dot"/> {staff?'議員・党職員・エリアサポーターの体験':'サポーター本人の体験'}</span><div><label className="ab-demo-account-picker">デモアカウント <select aria-label="統合デモのアカウント" value={data.actor.id} disabled={busy} onChange={event=>switchAccount(event.target.value)}>{data.demoAccounts.map(actor=><option key={actor.id} value={actor.id}>{actor.name}</option>)}</select></label><button disabled={busy} onClick={()=>switchAccount(staff?'s1':'staff-demo')}>{staff?'サポーターとして見る':'スタッフとして見る'} <ArrowRight size={13}/></button></div></div>
    {error&&<div className="ab-main"><div className="t-alert t-alert-error" role="alert">{error}</div></div>}
    {forbidden?<main className="ab-main"><div className="ab-empty"><LockKeyhole size={32}/><h1>この画面は{staff?'サポーター本人':'議員・党職員・エリアサポーター'}用です</h1><button className="ab-button" onClick={()=>switchAccount(staff?'s1':'staff-demo')}>対応するデモアカウントに切り替える</button></div></main>:<>
      {view==='home'?<BoardHome data={data} self={self} staff={staff} pending={pending} navigate={navigate} onSelect={setMission}/>:<main className="ab-main"><div className="ab-page-heading"><div><span className="ab-eyebrow">{staff?'STAFF WORKSPACE':'MY ACTION BOARD'}</span><h1>{titles[view]}</h1><p>{view==='missions'?'小さな一歩を、次の得意につなげよう。':view==='history'?'あなたが積み重ねたアクション。その経験は、次の活動にも活きていく。':view==='supporters'?'スキルと参加条件を見ながら、活動に合う仲間を探せます。':view==='team'?'必要な役割と人数から、仲間の得意が活きるチーム案を。':view==='activities'?'活動を登録し、必要な役割からチーム案へつなげます。':'活動と得意をつなぐ、Action Boardの新しい体験。'}</p></div>{staff&&view==='activities'&&<button className="ab-button primary" onClick={()=>setActivity('new')}><Plus size={17}/>活動を登録</button>}</div>
        {talentView&&<nav className="ab-talent-tabs" aria-label="マイタレントメニュー">{[{id:'talent',label:'タレント概要'},{id:'profile',label:'プロフィール編集'},{id:'suggestions',label:`発見候補${pending?` (${pending})`:''}`},{id:'interview',label:'AIインタビュー'},{id:'recommendations',label:'仲間の強みを推薦'}].map(item=><button key={item.id} onClick={()=>navigate(item.id)} className={view===item.id?'active':''} aria-current={view===item.id?'page':undefined}>{item.label}</button>)}</nav>}
        {staffView&&<nav className="ab-staff-tabs" aria-label="スタッフワークスペースメニュー">{[{id:'supporters',label:'サポーターを探す',Icon:Search},{id:'team',label:'チームをつくる',Icon:Users},{id:'activities',label:'活動を管理',Icon:CalendarDays}].map(({id,label,Icon})=><button key={id} onClick={()=>navigate(id)} className={view===id?'active':''}><Icon size={16}/>{label}</button>)}</nav>}
        {view==='account'&&<BoardMyPage data={data} navigate={navigate}/>}
        {view==='settings'&&<BoardAccountSettings data={data} navigate={navigate}/>}
        {view==='missions'&&<MissionBrowser data={data} onSelect={setMission}/>}
        {view==='history'&&<section className="ab-history">{data.board.achievements.length===0?<div className="ab-empty"><Footprints size={34}/><h2>最初のアクションを記録しよう</h2><p>ミッションを達成すると、ここに履歴が積み重なります。</p><button className="ab-button primary" onClick={()=>navigate('missions')}>ミッションを探す<ArrowRight size={16}/></button></div>:data.board.achievements.map(item=>{const suggestions=data.suggestions.filter(s=>item.suggestionIds.includes(s.id));return <article className="ab-history-item" key={item.id}><span className="ab-history-check"><Check size={23}/></span><div><small>{date(item.occurredAt)} · サンプル活動</small><h2>{item.title}</h2><p>{item.recordedRole?`記録した担当：${item.recordedRole}`:'参加記録のみ · 担当スキルは推測しません'}</p>{suggestions.length>0&&<button className="ab-skill-link" onClick={()=>navigate('suggestions')}><Sparkles size={15}/>{suggestions.map(s=>s.normalizedName).join('・')}<span>{suggestions.some(s=>s.status==='pending')?'本人確認待ち':suggestions.some(s=>s.status==='approved')?'タレントに反映済み':'確認済み'}</span><ChevronRight size={14}/></button>}</div><b>+{item.points}<small> P</small></b></article>})}</section>}
        {view==='talent'&&self&&<TalentOverview profile={self} pending={pending} data={data} navigate={navigate} onAction={action}/>}
        {['profile','suggestions','interview','recommendations'].includes(view)&&<SelfWorkspace key={`${data.actor.id}-${view}`} view={view as 'profile'} data={data} api={boardApi} onAction={action} onRefresh={refresh} onNavigate={navigate}/>}
        {view==='supporters'&&<SupporterSearch key={data.actor.id} profiles={data.profiles} api={boardApi} agreementSummaries={data.agreementSummaries} onDetail={setPerson}/>}
        {view==='team'&&<TeamBuilder key={teamPrompt} profiles={data.profiles} initialRequest={teamPrompt} savedTeams={data.teams} onAction={action} onRefresh={refresh} onDetail={setPerson} api={boardApi}/>}
        {view==='activities'&&<div className="ab-activity-grid">{data.activities.map(item=><article className="ab-card" key={item.id}><span className="ab-new">活動計画</span><h2>{item.title}</h2><p>{item.description}</p><div className="ab-meta"><CalendarDays size={15}/>{date(item.date)}<MapPin size={15}/>{item.location}</div><div className="ab-tag-row">{item.requiredSkills.map(skill=><span key={skill}>{skill}</span>)}</div><div className="ab-card-buttons"><button className="ab-button" onClick={()=>setActivity(item)}>編集</button><button className="ab-button primary" onClick={()=>{setTeamPrompt(`${item.title} ${item.location}。${item.requiredSkills.map(skill=>`${skill}1名`).join('、')}`);navigate('team')}}>チーム案をつくる<ArrowRight size={15}/></button></div></article>)}</div>}
        {view==='about'&&<About/>}
      </main>}
    </>}
    <footer className="ab-footer"><div><Sprout size={24}/><strong>Action Board <span>× Talent</span></strong><p>アクションの先に、ひとりひとりの可能性を。</p></div><span>非公式の統合提案・架空データのみ<br/>本番サービスへの接続・送信はありません</span><Link href="/">単独版 Talent Managementへ <ArrowRight size={14}/></Link></footer>
    {toast&&<div className="t-toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
    {mission&&<TalentModal title={mission.title} onClose={()=>setMission(null)}><MissionDialog key={mission.id} mission={mission} data={data} busy={busy} onComplete={async performedRole=>{setBusy(true);try{await action({action:'board.complete',missionId:mission.id,performedRole})}finally{setBusy(false)}}} onNext={()=>{setMission(null);navigate('suggestions')}} onHistory={()=>{setMission(null);navigate('history')}} onSupporter={()=>switchAccount('s1')}/></TalentModal>}
    {selected&&<TalentModal title="サポーター詳細" className="ab-supporter-modal" onClose={()=>setPerson(null)}><ProfileDetail profile={selected} data={data} onAction={action} onRecommend={()=>{setRecommend(selected);setPerson(null)}}/></TalentModal>}
    {recommend&&<TalentModal title="強みを推薦する" onClose={()=>setRecommend(null)}><QuickRecommendation profile={recommend} onSave={async text=>{await action({action:'recommendation.send',toId:recommend.id,text});setRecommend(null)}}/></TalentModal>}
    {activity&&<TalentModal title={activity==='new'?'活動を登録する':'活動を編集する'} onClose={()=>setActivity(null)}><ActivityEditor activity={activity==='new'?undefined:activity} onCancel={()=>setActivity(null)} onSave={async value=>{await action({action:'activity.save',activity:value});setActivity(null)}}/></TalentModal>}
  </div>
}

function BoardHome({data,self,staff,pending,navigate,onSelect}:{data:BoardBootstrap;self:TalentProfile|undefined;staff:boolean;pending:number;navigate:(view:string)=>void;onSelect:(mission:DemoMission)=>void}){
  const level=Math.max(1,Math.floor(data.board.points/200)+1)
  return <><section className="ab-home-hero"><div className="ab-home-hero-card">{self?<TalentAvatar profile={self} large/>:<span className="ab-staff-avatar"><Users size={30}/></span>}<div><strong>{self?.name||'議員・党職員・エリアサポーター（デモ）'}</strong><span><b>LV. {level}</b>{self&&<><MapPin size={15}/>{self.location}</>}</span><small>{data.board.points.toLocaleString()} ポイント（デモ）</small><div className="ab-home-progress"><i style={{width:`${Math.max(8,data.board.points%200/2)}%`}}/></div></div><button onClick={()=>navigate(staff?'supporters':'account')}>{staff?'人材を探す':'マイページを見る'}<ChevronRight size={15}/></button></div></section>
    <main className="ab-home-main"><div className="ab-home-notice"><ShieldCheck size={18}/><span>これは架空データの非公式統合デモです。ミッションやポイントは本家には反映されません。</span></div>
      <section className="ab-home-activity"><div><h2>チームみらいの活動状況🚀</h2><div className="ab-home-metrics"><span>このデモでの達成<strong>{data.board.achievements.length}<small>回</small></strong></span><span>サンプルサポーター<strong>{data.profiles.length}<small>人</small></strong></span></div></div><div><h2>⏰ 活動タイムライン</h2>{data.board.achievements.length?data.board.achievements.slice(0,2).map(item=><p key={item.id}>{item.title}を達成しました <small>{date(item.occurredAt)}</small></p>):<p>まだ記録はありません。気になるミッションから始めましょう。</p>}<button className="ab-original-link" onClick={()=>navigate('history')}>もっと見る<ArrowRight size={15}/></button></div></section>
      <section className="ab-home-mission-section"><div className="ab-section-heading"><div><h2>🚩 はじめのミッション</h2><p>まずはここから始めてみましょう</p></div><button className="ab-text-button" onClick={()=>navigate('missions')}>ミッションをもっと見る<ArrowRight size={16}/></button></div><MissionGrid missions={data.board.missions.slice(0,4)} data={data} onSelect={onSelect}/></section>
      <section className="ab-home-talent-addition"><div className="ab-addition-mark"><Sprout size={17}/>追加提案 · Talent Management</div><div className="ab-addition-body"><TalentIllustration scene="search"/><div><h2>活動の先に、あなたの得意が育つ。</h2><p>ミッションやアカウントはそのまま。活動経験、本人が承認したスキル、仲間の推薦を新しいタレント領域に蓄積します。</p><button className="ab-button primary" onClick={()=>navigate(staff?'supporters':pending?'suggestions':'account')}>{staff?'活動に合う仲間を探す':pending?`${pending}件の発見候補を見る`:'マイページで見る'}<ArrowRight size={16}/></button></div></div></section>
    </main>
  </>
}

function MissionGrid({missions,data,onSelect}:{missions:DemoMission[];data:BoardBootstrap;onSelect:(mission:DemoMission)=>void}){return <div className="ab-mission-grid">{missions.map(mission=>{const done=data.board.achievements.some(a=>a.missionId===mission.id);return <article className={`ab-mission-card ${mission.icon}`} key={mission.id}><div className="ab-mission-art"><span className="ab-mission-category">{mission.category}</span><TalentIllustration scene={mission.icon} className="ab-mission-scene"/><span className="ab-art-small"><Sparkles size={17}/></span>{done&&<span className="ab-done"><Check size={13}/>達成済み</span>}</div><div className="ab-mission-content"><div className="ab-meta"><MapPin size={13}/>{mission.location}<span>・{mission.duration}</span></div><h3>{mission.title}</h3><p>{mission.description}</p><div className="ab-mission-points"><span>難易度 <b>{'★'.repeat(mission.difficulty)}{'☆'.repeat(3-mission.difficulty)}</b></span><span><Award size={15}/>{mission.points} P</span></div>{mission.role&&<span className="ab-skill-hint"><Sprout size={14}/>{mission.role}の経験につながる</span>}<button className={`ab-button ${done?'':'primary'}`} onClick={()=>onSelect(mission)}>{done?'達成内容を見る':'ミッションを見る'}<ArrowRight size={16}/></button></div></article>})}</div>}
function MissionBrowser({data,onSelect}:{data:BoardBootstrap;onSelect:(mission:DemoMission)=>void}){const [filter,setFilter]=useState('すべて');return <><div className="ab-filters">{['すべて','地域で参加','オンライン','未達成'].map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div><MissionGrid missions={data.board.missions.filter(m=>filter==='すべて'||m.category===filter||(filter==='未達成'&&!data.board.achievements.some(a=>a.missionId===m.id)))} data={data} onSelect={onSelect}/></>}
function MissionDialog({mission,data,busy,onComplete,onNext,onHistory,onSupporter}:{mission:DemoMission;data:BoardBootstrap;busy:boolean;onComplete:(performedRole:boolean)=>Promise<void>;onNext:()=>void;onHistory:()=>void;onSupporter:()=>void}){
  const [role,setRole]=useState(''),[error,setError]=useState('');const achieved=data.board.achievements.find(a=>a.missionId===mission.id),Icon=icons[mission.icon]
  return <div className="ab-mission-dialog"><div className={`ab-dialog-icon ${mission.icon}`}><Icon size={38}/></div>{achieved?<><span className="ab-success-label"><CheckCircle2 size={17}/>デモミッション達成</span><h2>アクションが、経験になりました。</h2><p className="ab-earned">+{achieved.points}<small> P</small></p>{achieved.suggestionIds.length>0?<><div className="ab-next-talent"><Sparkles size={22}/><div><strong>「{achieved.recordedRole}」の候補が見つかりました</strong><p>まだプロフィールには登録されていません。内容を確かめて、あなたの言葉で承認しましょう。</p></div></div><button className="ab-button primary" onClick={onNext}>見つかったスキルを確認<ArrowRight size={17}/></button></>:<p>参加記録を保存しました。参加だけで運営能力などを推測することはありません。</p>}<button className="ab-text-button" onClick={onHistory}>活動履歴を見る<ArrowRight size={15}/></button></>:<><p>{mission.description}</p><div className="ab-meta"><MapPin size={15}/>{mission.location}<Clock3 size={15}/>{mission.duration}</div><ol className="ab-mission-steps">{mission.steps.map((step,index)=><li key={step}><b>{index+1}</b>{step}</li>)}</ol><div className="ab-demo-notice">実際の活動への申込・報告ではありません。架空のミッション達成を記録するデモです。</div>{data.actor.role==='staff'?<button className="ab-button" onClick={onSupporter}>サポーターとして体験する</button>:<form onSubmit={async event=>{event.preventDefault();setError('');try{await onComplete(role==='performed')}catch(cause){setError(cause instanceof Error?cause.message:'記録できませんでした')}}}>{mission.role&&<fieldset><legend>今回、担当した役割（デモ）</legend><label><input required type="radio" name="mission-role" value="performed" checked={role==='performed'} onChange={()=>setRole('performed')}/>{mission.role}を担当した</label><label><input required type="radio" name="mission-role" value="attendance" checked={role==='attendance'} onChange={()=>setRole('attendance')}/>参加のみ・担当の記録なし</label></fieldset>}{error&&<p className="t-alert t-alert-error" role="alert">{error}</p>}<button className="ab-button primary" disabled={busy||Boolean(mission.role&&!role)}><CheckCircle2 size={18}/>{busy?'保存中…':'デモの達成を記録する'}</button></form>}</>}</div>
}
function TalentOverview({profile,pending,data,navigate,onAction}:{profile:TalentProfile;pending:number;data:BoardBootstrap;navigate:(view:string)=>void;onAction:(payload:Record<string,unknown>)=>Promise<void>}){return <div className="ab-talent-overview"><section className="ab-talent-profile"><TalentAvatar profile={profile} large/><div><span className="ab-eyebrow">MY TALENT PROFILE</span><h2>{profile.name}</h2><p>{profile.headline}</p><span className="ab-meta"><MapPin size={14}/>{profile.location}</span></div><div className="ab-completion"><b>{completeness(profile).score}<small>%</small></b><span>プロフィール充実度</span></div></section><div className="ab-talent-columns"><section className="ab-card"><div className="ab-section-title"><h2><Sprout size={21}/>わたしの得意・経験</h2><button className="ab-text-button" onClick={()=>navigate('profile')}>編集<ChevronRight size={14}/></button></div><p>自分の言葉も、仲間の推薦も、活動の記録も。</p><div className="ab-skill-list">{profile.talents.map(skill=><div key={skill.id}><span className="ab-skill-icon"><BadgeCheck size={18}/></span><div><strong>{skill.normalizedName}</strong><small>{skill.originalText}</small></div><span className={`t-source t-source-${skill.source}`}>{SOURCE_LABELS[skill.source]}</span>{skill.source==='recommendation'&&<SkillAgreementButton skillId={skill.id} summary={data.agreementSummaries[skill.id]} onToggle={id=>onAction({action:'skill.agreement.toggle',skillId:id})} compact/>}</div>)}</div></section><aside><section className="ab-card ab-discovery"><TalentIllustration scene="praise" className="ab-discovery-scene"/><span className="ab-discovery-icon"><Sparkles size={25}/></span><h2>{pending?`${pending}件の強みが見つかっています`:'次の強みを、見つけよう。'}</h2><p>{pending?'活動から見つかった候補を確認しましょう。承認したものだけがプロフィールに加わります。':'ミッションへの参加やAIとの会話から、自分でも気づかなかった得意を見つけませんか。'}</p><button className="ab-button primary" onClick={()=>navigate(pending?'suggestions':'interview')}>{pending?'候補を確認する':'AIと話してみる'}<ArrowRight size={15}/></button></section><section className="ab-card"><h3><History size={19}/>活動から育つタレント</h3><p>デモミッション達成 <strong>{data.board.achievements.length}回</strong></p><button className="ab-text-button" onClick={()=>navigate('history')}>経験の記録を見る<ArrowRight size={15}/></button></section><button className="ab-button" onClick={()=>navigate('recommendations')}><HeartHandshake size={17}/>仲間の強みを推薦する</button></aside></div></div>}
function Journey({navigate,staff}:{navigate:(view:string)=>void;staff:boolean}){return <section className="ab-journey"><span className="ab-eyebrow">EVERY ACTION GROWS YOUR TALENT</span><h2>活動の記録が、次の出会いへ。</h2><div>{[{Icon:Flag,title:'アクションする',text:'ミッションに参加して、経験を積み重ねる。',view:'missions'},{Icon:Sparkles,title:'得意を見つける',text:'活動記録からスキル候補。本人が確認・承認。',view:staff?'supporters':'suggestions'},{Icon:Users,title:'チームにつながる',text:'得意と参加できる条件から、次の仲間を探す。',view:staff?'team':'talent'}].map(({Icon,title,text,view},index)=><button key={title} onClick={()=>navigate(view)}><span><Icon size={25}/></span><small>0{index+1}</small><h3>{title}</h3><p>{text}</p><ArrowRight size={17}/></button>)}</div><p>能力と活動意欲は別々に。AIが参加や評価を自動で確定することはありません。</p></section>}
function About(){return <div className="ab-about"><section className="ab-card"><span className="ab-new">INTEGRATION CONCEPT</span><h2>いつものAction Boardに、タレントの層を。</h2><p>公開コードと公開画面のミッション・ポイント・活動履歴・プロフィール・アカウント設定という構成を参考にした、独立実装のサンプルです。本家の完全な複製ではありません。</p><p>本家の公開トップ・公開プロフィールを読み取り専用で確認し、公開ソースの画面構成も参照しました。公式の認証・Supabase・Slack・分析SDK・画像配信は使いません。</p></section><section className="ab-card"><h2>本当に統合する場合の対応</h2><div className="ab-mapping"><div><strong>本家のログイン</strong><ArrowRight size={18}/><span>同じユーザーIDにTalent Profileを追加</span></div><div><strong>ミッション達成・担当記録</strong><ArrowRight size={18}/><span>Skill Evidenceと本人確認待ち候補</span></div><div><strong>マイページ</strong><ArrowRight size={18}/><span>スキル・経験・参加条件をまとめて管理</span></div><div><strong>スタッフの活動管理</strong><ArrowRight size={18}/><span>理由付き検索・候補チームの検討</span></div></div></section><section className="ab-card"><h2>このデモの境界</h2><p>データとセッションは単独版v0.2からも分離しています。ミッション・ポイント・人物・活動日程はすべて架空です。AIはローカルのルールによるMockで、外部への連絡・送信は行いません。</p><p>参照元：team-mirai-volunteer/action-board<br/>参照commit：1b269081aaee4a145a125af46d5c90b88d9e5a4e<br/>本家のコード・画像素材はこの画面にコピーしていません。</p></section></div>}
